### ISSUE TITLE
응원합니다

### ISSUE THREAD

**Issue by icepeng** [hi098123/smwar#1]
![유효옵 설정](https://i.imgur.com/U9bcmNu.png)
![룬 관리](https://i.imgur.com/Hpeo9fc.png)

[Link](https://icepeng.github.io/sw-penguin/)

이런걸 만드는 사람입니다.

이걸 만든 죄로 공카에서 밴을 먹긴 했지만...

[SW Exporter](https://github.com/Xzandro/sw-exporter)

[SWAG](https://github.com/Xzandro/Swag)

길전 관련이니 이런걸 어떻게 연동해서 자동화할 방법도 떠올려볼수 있겠네요.

앞으로도 계속 좋은 툴 만들어내시길 응원합니다.

**Comment by hi098123** [comment]
와 이런거 만들었다고 밴을...
연동하는건 중간에 데이터를 가져가는거라 밴을 먹이는건가..
제껀 별거없이 덧셈 뺄셈 곱셈 나눗셈 사칙연산만 하는걸요..
